PGSTask.Web_Jakub_Rzepka/Models/UserTask.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace PGSTask.Web_Jakub_Rzepka.Models
{
    public class UserTask
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Description { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy HH:mm}")]
        [Required, DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime CreatedAt { get; set; }

        public bool IsDone { get; set; }
    }
}

PGSTask.Web_Jakub_Rzepka/ViewModels/UserTaskViewModel.cs
using PGSTask.Web_Jakub_Rzepka.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using PGSTask.Web_Jakub_Rzepka;
using X.PagedList;

namespace PGSTask.Web_Jakub_Rzepka.ViewModels
{
    public class UserTaskViewModel
    {
        [Required]
        public string Description { get; set; }

        public IPagedList<UserTask> Tasks { get; set; }
        
        public string SortOrder { get;  set; }
        public string CurrentColumn { get;  set; }
        public string CurrentFilter { get;  set; }

        public string GetInverseSortOrder() =>
            SortOrder == Web_Jakub_Rzepka.SortOrder.Desc || SortOrder == null ? Web_Jakub_Rzepka.SortOrder.Asc : Web_Jakub_Rzepka.SortOrder.Desc;
    }
}

PGSTask.Web_Jakub_Rzepka/Controllers/UserTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PGSTask.Web_Jakub_Rzepka.Models;
using PGSTask.Web_Jakub_Rzepka.ViewModels;
using System.Linq.Dynamic;
using PGSTask.Web_Jakub_Rzepka.Repositories;

namespace PGSTask.Web_Jakub_Rzepka.Controllers
{
    public class UserTaskController : Controller
    {
        private readonly IUserTaskRepository _userTaskRepository;

        public UserTaskController(IUserTaskRepository userTaskRepository)
        {
            _userTaskRepository = userTaskRepository;
        }

        // GET: Task
        public ActionResult Index(string column = null, string sortOrder = null, string searchString = null, int? page = null)
        {
            var tasksVM = new UserTasksVM();

            tasksVM.SortOrder = sortOrder;
            tasksVM.Tasks = _userTaskRepository.GetAllTasks(column, sortOrder, searchString, page);

            tasksVM.CurrentColumn = column;
            tasksVM.CurrentFilter = searchString;

            return View(tasksVM);
        }


        // POST: Task/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Description")] CreateTaskVM model)
        {
            if (ModelState.IsValid)
                _userTaskRepository.AddTask(model);
            
            return RedirectToAction("Index");
        }

        // POST: Task/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(int id, string description)
        {
            if (!String.IsNullOrEmpty(description))
            {
                _userTaskRepository.EditTask(id, description);

                return Json(new { success = true, responseText = id });
            }
            return Json(new { success = false, responseText = id });
        }

        // POST: Task/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            _userTaskRepository.DeleteTask(id);
            return RedirectToAction("Index");
        }
    }
}

PGSTask.Web_Jakub_Rzepka/Views/UserTask/Index.cshtml
@model UserTasksVM
@using X.PagedList.Mvc.Core; 
@using X.PagedList; 


@{
    ViewData["Title"] = "Task list";
}



<div class="row text-light mt-4 mb-2 pt-5">
    <div class="col-12 text-center">
        <h1>Task List</h1>
    </div>
</div>
<div class="row">
    <div class="col-12 text-center">
        <form asp-controller="UserTask" asp-action="Create" method="post" id="submitForm">
            @Html.AntiForgeryToken()
            <div class="input-group p-5">
                <input type="text" class="form-control w-75 rounded p-4" placeholder="Enter your task..." name="Description" id="submitInput">
                <span asp-validation-for="Description" class="text-danger"></span>
                <div class="w-25 text-right">
                    <button type="button" class="btn btn-warning w-75 font-weight-bold customBtn" id="submitBtn">Add</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card p-2 mb-1 customCard ">
            <form asp-controller="UserTask" asp-action="Index" method="get">
                <div class="input-group">
                    <input type="hidden" name="column" value="@Model.CurrentColumn">
                    <input type="hidden" name="sortOrder" value="@Model.SortOrder">
                    <input type="text" class="form-control rounded mr-5" placeholder="Task description..." name="searchString" value="@Model.CurrentFilter">
                    <div class="mr-3">
                        <button class="btn btn-secondary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <table class="table table-hover bg-light m-0">
                <thead class="bg-dark text-light">
                    <tr>
                        <td class="max-width-5 text-center">
                            @Html.ActionLink("Description", "Index", new { sortOrder = Model.GetInverseSortOrder(), column = nameof(UserTask.Description), searchString = Model.CurrentFilter }, new { @class = "customLink" })
                        </td>
                        <td class="text-right max-width-03 text-right pr-4">
                            @Html.ActionLink("Created at", "Index", new { sortOrder = Model.GetInverseSortOrder(), column = nameof(UserTask.CreatedAt), searchString = Model.CurrentFilter }, new { @class = "customLink" })
                        </td>
                        <td class="border-left text-center max-width-02"></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var task in Model.Tasks)
                    {
                        <tr>
                            <td class="max-width-5">
                                <input class="w-100 customInput" value="@task.Description" readonly name="@task.Id" />
                            </td>
                            <td class="text-right text-pale max-width-03">
                                <span class="border-left pl-1">@Html.DisplayFor(modelItem => task.CreatedAt)</span>
                            </td>
                            <td class="border-left text-center max-width-02">
                                    <i class="fas fa-edit customEditIcon" name="@task.Id"></i>
                                    <i class="fas fa-check-circle customDoneIcon" id="@task.Id" style="display:none;"></i>
                                <form asp-controller="UserTask" asp-action="Delete" method="post" class="mr-2 ml-2 d-inline customForm" name="@task.Id">
                                    <input type="hidden" name="Id" value="@task.Id" readonly />
                                    <button type="submit" class="plain"><i class="fas fa-trash-alt customBinIcon"></i></button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@Html.PagedListPager((IPagedList)Model.Tasks, page => Url.Action("Index", new { page }))